### ISSUE TITLE
when i installed it. it gave me this

### ISSUE THREAD

**Issue by HidanOnCord** [Rdimo/pip-install-bitches#10]
bitches already satisfied 
![image](https://user-images.githubusercontent.com/100303736/158966416-b2b1297b-7bd9-4431-b0c0-761d8f1e5483.png)

**Comment by Nostorian** [comment]
that means the bitches are already installed in your pc, you dont need to run `pip install bitches` now on this machine

**Comment by HidanOnCord** [comment]
> that means the bitches are already installed in your pc, you dont need to run `pip install bitches` now on this machine

cuz i already have bitches

**Comment by Nostorian** [comment]
> > that means the bitches are already installed in your pc, you dont need to run `pip install bitches` now on this machine
> 
> cuz i already have bitches
> 

If u know that then why tf u ask this?

**Comment by HidanOnCord** [comment]
> > > that means the bitches are already installed in your pc, you dont need to run `pip install bitches` now on this machine
> > 
> > 
> > cuz i already have bitches
> 
> If u know that then why tf u make this issue?

ur so dumb it means i already have bitches

**Comment by Nostorian** [comment]
Wow I totally did not know that, and obv don't even know who python works, thanks for letting me know

**Comment by HidanOnCord** [comment]
> Wow I totally did not know that, and obv don't even know who python works, thanks for letting me know

even if u know python u dont know jokes even tho ur a joke ur self

**Comment by Nostorian** [comment]
Imagine trying to trash talk a sentence which is overused atleast a million times, atleast original content lol

**Comment by HidanOnCord** [comment]
stfu atleast i understand simple sarcasm

**Comment by HidanOnCord** [comment]
im pretty sure ur so black u fear the 1800s

**Comment by Nostorian** [comment]
> stfu atleast i understand simple sarcasm
> 

Did I ask that whether you understand sarcasm or not plus it would be pathetic if you wouldn't get it, so you don't need to flex basic abilities

**Comment by Nostorian** [comment]
> im pretty sure ur so black u fear the 1800s

Totally out of the way context, but since I consider you retarded I will say it's normal for you to talk like that

**Comment by Nostorian** [comment]
Also if you talk about me not understand the joke and that's pathetic as well, let me remind you the way you posted your issue it clearly looked like you didn't understand what was going on in the terminal, if you meant to intend it as a joke you should given it a caption or maybe done whatever to show that it's not a serious issue and you know what's going on

**Comment by Nostorian** [comment]
So if anything it's you who don't understand how to make jokes
